name: pix2pix
dependencies:
  - python=3.*
  - opencv
  - pillow
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - jupyter
  - pip:
    - tensorflow-gpu==1.13.1
    - dominate==2.3.1
    - scikit-image==0.14.2
    - git+https://www.github.com/keras-team/keras-contrib.git