name: pix2pix
dependencies:
  - python=3.*
  - tensorflow-gpu
  - opencv
  - pillow
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - jupyter
  - dominate=2.3.1
  - pip:
    - scikit-image==0.14.2
    - git+https://www.github.com/keras-team/keras-contrib.git